# These are supported funding model platforms
# Uncomment and fill in the ones you want to use

# github: [YOUR_USERNAME]
# patreon: YOUR_PATREON_USERNAME
# open_collective: YOUR_OPENCOLLECTIVE_USERNAME
# ko_fi: YOUR_KOFI_USERNAME
# custom: ["https://your-link.com"]
